2025-05-04 10:28:38,958:DEBUG:certbot._internal.main:certbot version: 2.10.0
2025-05-04 10:28:38,959:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2025-05-04 10:28:38,959:DEBUG:certbot._internal.main:Arguments: ['-v', '--webroot', '--agree-tos', '--renew-by-default', '--preferred-challenges', 'http-01', '--email', 'vaxelaire.yohem@gmail.com', '--webroot-path', '/var/www/certbot', '-d', 'hackthebox.vaxelaire.fr', '-n']
2025-05-04 10:28:38,959:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-05-04 10:28:39,006:DEBUG:certbot._internal.log:Root logging level set at 20
2025-05-04 10:28:39,007:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2025-05-04 10:28:39,008:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7ffb48f3de50>
Prep: True
2025-05-04 10:28:39,008:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7ffb48f3de50> and installer None
2025-05-04 10:28:39,008:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2025-05-04 10:28:39,058:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2243553505', new_authzr_uri=None, terms_of_service=None), b674a225a17192af95a621d2ec1bc036, Meta(creation_dt=datetime.datetime(2025, 2, 22, 10, 55, 38, tzinfo=<UTC>), creation_host='faa0276bdd8e', register_to_eff=None))>
2025-05-04 10:28:39,059:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-05-04 10:28:39,061:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-05-04 10:28:39,461:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 1012
2025-05-04 10:28:39,461:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 May 2025 10:28:39 GMT
Content-Type: application/json
Content-Length: 1012
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "fsHChmOr7Sc": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "https://letsencrypt.org/docs/profiles#classic",
      "shortlived": "https://letsencrypt.org/docs/profiles#shortlived (not yet generally available)",
      "tlsserver": "https://letsencrypt.org/docs/profiles#tlsserver"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.5-February-24-2025.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-05-04 10:28:39,482:DEBUG:certbot._internal.renewal:Auto-renewal forced with --force-renewal...
2025-05-04 10:28:39,482:DEBUG:certbot._internal.display.obj:Notifying user: Renewing an existing certificate for hackthebox.vaxelaire.fr
2025-05-04 10:28:39,484:DEBUG:acme.client:Requesting fresh nonce
2025-05-04 10:28:39,484:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-05-04 10:28:39,616:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-05-04 10:28:39,617:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 May 2025 10:28:39 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: aJoEAs1InG8t8lj1MjTousRwqLjCZODFTPHM1s5eOw2QKzdFpnM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-05-04 10:28:39,617:DEBUG:acme.client:Storing nonce: aJoEAs1InG8t8lj1MjTousRwqLjCZODFTPHM1s5eOw2QKzdFpnM
2025-05-04 10:28:39,618:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "hackthebox.vaxelaire.fr"\n    }\n  ]\n}'
2025-05-04 10:28:39,620:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJhSm9FQXMxSW5HOHQ4bGoxTWpUb3VzUndxTGpDWk9ERlRQSE0xczVlT3cyUUt6ZEZwbk0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "EsS7u5lCRPPfGwPLA5Pz0MoSQJtlA8dmsJ5thyl3BKebP8Ym-uszcor3BFzUlO8xFYZIvJt4kOQx8J2QeQuCZcVY-nEJO0GoTVW1unLGNF1093ubVrXINsYVM7euNtHUUY9UdHMScXfdPr3RJOMSdWDxE5DshwjCSMhvvgATmCy2yVuXbbnChU6JkB__jbszR51Pi1tC3O_BJvdnjuCIMuJYKIPKSb3W8ts7pFh3tr_GQAPLGNdpkJyGu_oj3aaefTWX0UFE-v1Tsl2yDk73eLeU5i-8AGEVWqSC4OINwdCv4sf_xxr7ZHBmSx0oDQPXkicWKok4r_mwYoSwJpgmGQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImhhY2t0aGVib3gudmF4ZWxhaXJlLmZyIgogICAgfQogIF0KfQ"
}
2025-05-04 10:28:39,801:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 357
2025-05-04 10:28:39,801:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 04 May 2025 10:28:39 GMT
Content-Type: application/json
Content-Length: 357
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2243553505/380699467817
Replay-Nonce: FIfrddYQu1_frAin5xd0sjH1_x6maXVy1YAv6AHY9fo1scVt-e8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-05-11T10:28:39Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "hackthebox.vaxelaire.fr"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/515318672177"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2243553505/380699467817"
}
2025-05-04 10:28:39,801:DEBUG:acme.client:Storing nonce: FIfrddYQu1_frAin5xd0sjH1_x6maXVy1YAv6AHY9fo1scVt-e8
2025-05-04 10:28:39,802:DEBUG:acme.client:JWS payload:
b''
2025-05-04 10:28:39,803:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/515318672177:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJGSWZyZGRZUXUxX2ZyQWluNXhkMHNqSDFfeDZtYVhWeTFZQXY2QUhZOWZvMXNjVnQtZTgiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIyNDM1NTM1MDUvNTE1MzE4NjcyMTc3In0",
  "signature": "PRl5nlhw4ccnDztNvJVw2uL8ezQTZIVQNr4BZDvVELZ6JwTCqaun4XxxMpbGAWAs_MB_4PWYdw0dr-FpoAmF3A2IvAAobFcDEib3_LwnMr0KEH9uEYY4_G24XUV12dhEO9Mpc1dS_hdApUSCu7EA8XNG64IvxfcI7dfB2LLlotlp5t4vtLefy_nXCpwU7V0Qz7x2Qt1UkQvgJp4TEnnFAk1RcZ67wJBpONRk3Owtj78zgakN-YRnQLzy16J0PSIUP6mU9AKUASYwtsZt8o1_KZ-7phOxbmH2DJpL1Ez9KHM52RGAeHoduJzgCuKFy2O7DuwDxJhNGUwTMS0Mn6_blQ",
  "payload": ""
}
2025-05-04 10:28:39,946:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2243553505/515318672177 HTTP/1.1" 200 831
2025-05-04 10:28:39,946:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 May 2025 10:28:39 GMT
Content-Type: application/json
Content-Length: 831
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: FIfrddYQiaGQP1BqhxILIHsbCMEEI9VejzlUdGWCHxXLChBgN4Y
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "hackthebox.vaxelaire.fr"
  },
  "status": "pending",
  "expires": "2025-05-11T10:28:39Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/Mxuorw",
      "status": "pending",
      "token": "DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/LW166g",
      "status": "pending",
      "token": "DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/QJyBYw",
      "status": "pending",
      "token": "DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk"
    }
  ]
}
2025-05-04 10:28:39,947:DEBUG:acme.client:Storing nonce: FIfrddYQiaGQP1BqhxILIHsbCMEEI9VejzlUdGWCHxXLChBgN4Y
2025-05-04 10:28:39,947:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-05-04 10:28:39,947:INFO:certbot._internal.auth_handler:http-01 challenge for hackthebox.vaxelaire.fr
2025-05-04 10:28:39,947:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2025-05-04 10:28:39,948:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2025-05-04 10:28:39,948:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk
2025-05-04 10:28:39,949:DEBUG:acme.client:JWS payload:
b'{}'
2025-05-04 10:28:39,950:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/Mxuorw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJGSWZyZGRZUWlhR1FQMUJxaHhJTElIc2JDTUVFSTlWZWp6bFVkR1dDSHhYTENoQmdONFkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIyNDM1NTM1MDUvNTE1MzE4NjcyMTc3L014dW9ydyJ9",
  "signature": "FZLdODSqS8IIK0BPTtZWqiBtl0ApUGcrk3IbMBR5NIKtN5cMBpBSp7-fzzKC2yi76eJlNdSjKHTsTaTYiwz68Pqj_dQz8t7E8RhRySdVpfXt7SjGrOiTmPeiq5uTa8Q8JJhX-VxvP8Py1bEZGJd5nC9hSFEjSOkOvaZnX6WTOFYeJVwcxGE3MKv5tsWQRAEZtKcNLVrnmRiwJpR3BbEhR9S2OYU-CM5IeSYoRl_3AnFblu4343UGWetBevGKwrbtYq3KXIVj3jUwfW5fQ1ktJMT8Iud1edFdBgdzcFvrHiYVbHh7uPUAVDEgAi8qHayzXnnJKVn4rfSQscVxWup_Bg",
  "payload": "e30"
}
2025-05-04 10:28:40,102:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2243553505/515318672177/Mxuorw HTTP/1.1" 200 195
2025-05-04 10:28:40,103:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 May 2025 10:28:40 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/515318672177>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/Mxuorw
Replay-Nonce: FIfrddYQeuv6ycr_9eM4CLU2Iw4WVCxOYOmp4jHyT4VCOTbYxHw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/Mxuorw",
  "status": "pending",
  "token": "DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk"
}
2025-05-04 10:28:40,103:DEBUG:acme.client:Storing nonce: FIfrddYQeuv6ycr_9eM4CLU2Iw4WVCxOYOmp4jHyT4VCOTbYxHw
2025-05-04 10:28:40,103:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-05-04 10:28:41,103:DEBUG:acme.client:JWS payload:
b''
2025-05-04 10:28:41,105:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/515318672177:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJGSWZyZGRZUWV1djZ5Y3JfOWVNNENMVTJJdzRXVkN4T1lPbXA0akh5VDRWQ09UYll4SHciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIyNDM1NTM1MDUvNTE1MzE4NjcyMTc3In0",
  "signature": "J_2M0nQ3BIfj7OLkRJCQGJFchLy0QopfELXrtxFcWmBQTuLcB1OEuLFBpilz_pXZdTkR-oWe9dtNYSjqoJakDIL6Fjhr56cQpb0wVQWfbQ06Bu9fsZJID7xT3IltDq3bhaY66iRmnMoK0HtTFR5V59U3F8UXHACHDaPwbER9eiaicZ-UfNXBKqXCX4OhdynJ4JwvEQzRTKz1DdmFnyCBHkKP0PK9eQp-aweJiqS2JAYB9UyjAsFLrIUtfBFr5XtSY1-4qHzb5BqQPjdAs-ZYmXEplRlg4sRhd3lRbCXIv445XwQZxzGv1AejCSJ8nsQbHwFxC9EE3aaF-ZeV2xtTDQ",
  "payload": ""
}
2025-05-04 10:28:41,244:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2243553505/515318672177 HTTP/1.1" 200 1489
2025-05-04 10:28:41,244:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 04 May 2025 10:28:41 GMT
Content-Type: application/json
Content-Length: 1489
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: FIfrddYQ2dVbiZ6WzODEWsfTv8LIiT-3t_HkJvUVG9Se6kc_HXY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "hackthebox.vaxelaire.fr"
  },
  "status": "invalid",
  "expires": "2025-05-11T10:28:39Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/515318672177/Mxuorw",
      "status": "invalid",
      "validated": "2025-05-04T10:28:40Z",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "91.108.113.88: Fetching http://hackthebox.vaxelaire.fr/.well-known/acme-challenge/DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk: Error getting validation data",
        "status": 400
      },
      "token": "DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk",
      "validationRecord": [
        {
          "url": "http://hackthebox.vaxelaire.fr/.well-known/acme-challenge/DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk",
          "hostname": "hackthebox.vaxelaire.fr",
          "port": "80",
          "addressesResolved": [
            "91.108.113.88",
            "2a02:4780:28:d15a::1"
          ],
          "addressUsed": "2a02:4780:28:d15a::1"
        },
        {
          "url": "http://hackthebox.vaxelaire.fr/.well-known/acme-challenge/DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk",
          "hostname": "hackthebox.vaxelaire.fr",
          "port": "80",
          "addressesResolved": [
            "91.108.113.88",
            "2a02:4780:28:d15a::1"
          ],
          "addressUsed": "91.108.113.88"
        }
      ]
    }
  ]
}
2025-05-04 10:28:41,245:DEBUG:acme.client:Storing nonce: FIfrddYQ2dVbiZ6WzODEWsfTv8LIiT-3t_HkJvUVG9Se6kc_HXY
2025-05-04 10:28:41,245:INFO:certbot._internal.auth_handler:Challenge failed for domain hackthebox.vaxelaire.fr
2025-05-04 10:28:41,245:INFO:certbot._internal.auth_handler:http-01 challenge for hackthebox.vaxelaire.fr
2025-05-04 10:28:41,246:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: hackthebox.vaxelaire.fr
  Type:   connection
  Detail: 91.108.113.88: Fetching http://hackthebox.vaxelaire.fr/.well-known/acme-challenge/DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk: Error getting validation data

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2025-05-04 10:28:41,247:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-05-04 10:28:41,247:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-05-04 10:28:41,247:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-05-04 10:28:41,247:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/DecE_VneyALYzMNWPJtqY9ErAVIoYgIIUvI0UFiCibk
2025-05-04 10:28:41,248:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2025-05-04 10:28:41,248:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/main.py", line 131, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3.12/site-packages/certbot/_internal/renewal.py", line 399, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-05-04 10:28:41,251:ERROR:certbot._internal.log:Some challenges have failed.
