2025-02-22 13:36:44,353:DEBUG:certbot._internal.main:certbot version: 2.10.0
2025-02-22 13:36:44,354:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2025-02-22 13:36:44,354:DEBUG:certbot._internal.main:Arguments: ['-v', '--webroot', '--agree-tos', '--renew-by-default', '--preferred-challenges', 'http-01', '--email', 'vaxelaire.yohem@gmail.com', '--webroot-path', '/var/www/certbot', '--cert-name', 'vaxelaire.fr', '-d', 'vaxelaire.fr', '-n']
2025-02-22 13:36:44,354:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-02-22 13:36:44,372:DEBUG:certbot._internal.log:Root logging level set at 20
2025-02-22 13:36:44,373:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2025-02-22 13:36:44,373:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f5572fca0c0>
Prep: True
2025-02-22 13:36:44,373:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f5572fca0c0> and installer None
2025-02-22 13:36:44,373:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2025-02-22 13:36:44,423:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2243553505', new_authzr_uri=None, terms_of_service=None), b674a225a17192af95a621d2ec1bc036, Meta(creation_dt=datetime.datetime(2025, 2, 22, 10, 55, 38, tzinfo=<UTC>), creation_host='faa0276bdd8e', register_to_eff=None))>
2025-02-22 13:36:44,423:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2025-02-22 13:36:44,426:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2025-02-22 13:36:44,845:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 1038
2025-02-22 13:36:44,845:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 22 Feb 2025 13:36:44 GMT
Content-Type: application/json
Content-Length: 1038
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "iUC34mfIkVU": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "https://letsencrypt.org/docs/profiles#classic",
      "shortlived": "https://letsencrypt.org/docs/profiles#shortlived (not yet generally available)",
      "tlsserver": "https://letsencrypt.org/docs/profiles#tlsserver (not yet generally available)"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-02-22 13:36:44,846:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for vaxelaire.fr
2025-02-22 13:36:44,849:DEBUG:acme.client:Requesting fresh nonce
2025-02-22 13:36:44,849:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2025-02-22 13:36:44,984:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-02-22 13:36:44,985:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 22 Feb 2025 13:36:44 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: nCc9NVNmW4eFqoekOIhnCDavEDlnp1u3tN1zQfFtpMMLpU_Na1k
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-02-22 13:36:44,985:DEBUG:acme.client:Storing nonce: nCc9NVNmW4eFqoekOIhnCDavEDlnp1u3tN1zQfFtpMMLpU_Na1k
2025-02-22 13:36:44,985:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "vaxelaire.fr"\n    }\n  ]\n}'
2025-02-22 13:36:44,987:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJuQ2M5TlZObVc0ZUZxb2VrT0lobkNEYXZFRGxucDF1M3ROMXpRZkZ0cE1NTHBVX05hMWsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "QJ5BHN8E7RqQr1swWTfT8BdLESbe9TsW4u81LyDNS9_Siw4DK9ldfNpacKfpzn8Heepj9ywbX8FBkCrWiFzsIBOf0NuxVqaCqNjui3bsv2EII2_bPeii1uDItYmDMM3zHLXk7I9xxHn80GMxu7qECoxYVbzEP8DsgGAxKCSTLWIbAOksYbag2UmY-mcnZc27ZZZ0fdG4MPBgbiVERZDxhR3vZEkfgrX1PdnowZ1SEgNvR6j2RHLBU87_V1rFEJJfP3UFC0HVDdzh4PwvQSOfPaXIcAOk50eGHTxlmq0lUW-t2h5nH9KS1g5vuaPwagSEBlkyI-jEzJopqtIK5uAiig",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInZheGVsYWlyZS5mciIKICAgIH0KICBdCn0"
}
2025-02-22 13:36:45,178:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 346
2025-02-22 13:36:45,179:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sat, 22 Feb 2025 13:36:45 GMT
Content-Type: application/json
Content-Length: 346
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2243553505/356939534445
Replay-Nonce: bmVxADwsOEoCFE3Gi7xnczoVxYwsg7-5cszfyykbURJzh64jeM0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-03-01T13:36:45Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "vaxelaire.fr"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/479847063865"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2243553505/356939534445"
}
2025-02-22 13:36:45,179:DEBUG:acme.client:Storing nonce: bmVxADwsOEoCFE3Gi7xnczoVxYwsg7-5cszfyykbURJzh64jeM0
2025-02-22 13:36:45,179:DEBUG:acme.client:JWS payload:
b''
2025-02-22 13:36:45,180:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/479847063865:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJibVZ4QUR3c09Fb0NGRTNHaTd4bmN6b1Z4WXdzZzctNWNzemZ5eWtiVVJKemg2NGplTTAiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIyNDM1NTM1MDUvNDc5ODQ3MDYzODY1In0",
  "signature": "FmpMFu-13eIvJBohpngEB-scT1Il25uTrJjmrdUpYO0NeDJXQE3VPW2MV-k7xqEvOQpuPd21Rj4Z2Bna9pHv0tiKioSlKYJKomJPw6dak1GR1v5_X90cpR21BsmDsrnjzwNI9E9dtqTJEFXPo3hMrFIkQ6G9e7P1uEM-EGGqVyoGK7OlTQT8R11JC6UDq3VEUbG_cB2XJxHbsTfsxoz_yUdzt2RU4X_q7R-ySK6yZ4CvPXuUk3uZ8fJq-A7HFxpmTCFgg7gUH8rTxllF7E1OA75QVbWVc-mDED__1YNwa-hDysF2jGds1CHO0R6MW_e1Z7TT0e6A6RWQcHBhZjkK_Q",
  "payload": ""
}
2025-02-22 13:36:45,333:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2243553505/479847063865 HTTP/1.1" 200 820
2025-02-22 13:36:45,334:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 22 Feb 2025 13:36:45 GMT
Content-Type: application/json
Content-Length: 820
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: nCc9NVNm6wZb_0QRfyEtiTOnnXkFOw9BQh7xAYGXYdRFvHruI9w
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "vaxelaire.fr"
  },
  "status": "pending",
  "expires": "2025-03-01T13:36:45Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/2rByHg",
      "status": "pending",
      "token": "XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/hlRTKQ",
      "status": "pending",
      "token": "XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/B18DQA",
      "status": "pending",
      "token": "XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0"
    }
  ]
}
2025-02-22 13:36:45,334:DEBUG:acme.client:Storing nonce: nCc9NVNm6wZb_0QRfyEtiTOnnXkFOw9BQh7xAYGXYdRFvHruI9w
2025-02-22 13:36:45,335:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-02-22 13:36:45,335:INFO:certbot._internal.auth_handler:http-01 challenge for vaxelaire.fr
2025-02-22 13:36:45,335:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2025-02-22 13:36:45,335:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2025-02-22 13:36:45,337:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0
2025-02-22 13:36:45,337:DEBUG:acme.client:JWS payload:
b'{}'
2025-02-22 13:36:45,338:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/hlRTKQ:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJuQ2M5TlZObTZ3WmJfMFFSZnlFdGlUT25uWGtGT3c5QlFoN3hBWUdYWWRSRnZIcnVJOXciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIyNDM1NTM1MDUvNDc5ODQ3MDYzODY1L2hsUlRLUSJ9",
  "signature": "FtrhUZEBY2RtlsJEIAIcsQDhSTzYg9mF_fXzGmgkkO6QtmEeHHzUZJ2QNdW2DA4t_Fz7WrddrtSRAJkspDPeFHMEmAx3mzDFKVAarD4F9i2-2PK8cpVC8LCasE8uSXMKNFBdGpbhbWB3J7-2Wogs0mOZtltsDS5xGBZQdr11LPzFSG-VSFg1AprCMVB5cLRy-jpISuXAvpghEVJ52siMJ3tMbdIgtYYy73_4k_v8GoPCnOzO5h-XQ8IWvXR1yUgZ2o7Sh1y9QdqvY2ff0CRFULJquZp2n5u4eVHbZGehB7Tw5tcS4rm8OrJxKpXt1FpGU1k-oPosD7mYQweL7NxeRQ",
  "payload": "e30"
}
2025-02-22 13:36:45,480:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2243553505/479847063865/hlRTKQ HTTP/1.1" 200 195
2025-02-22 13:36:45,481:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 22 Feb 2025 13:36:45 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/479847063865>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/hlRTKQ
Replay-Nonce: bmVxADwsV9mskBi9LkUnvJYFZtxW5DmYFM4pe-P2x0X0aWh4G6w
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/hlRTKQ",
  "status": "pending",
  "token": "XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0"
}
2025-02-22 13:36:45,481:DEBUG:acme.client:Storing nonce: bmVxADwsV9mskBi9LkUnvJYFZtxW5DmYFM4pe-P2x0X0aWh4G6w
2025-02-22 13:36:45,482:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-02-22 13:36:46,482:DEBUG:acme.client:JWS payload:
b''
2025-02-22 13:36:46,484:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2243553505/479847063865:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjI0MzU1MzUwNSIsICJub25jZSI6ICJibVZ4QUR3c1Y5bXNrQmk5TGtVbnZKWUZadHhXNURtWUZNNHBlLVAyeDBYMGFXaDRHNnciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIyNDM1NTM1MDUvNDc5ODQ3MDYzODY1In0",
  "signature": "AJc2CWWD7Np3dYO7eBgSKuy8TsO6cVevdJYJaFMmVrmU_vW3D42PLGXfhBIDLA-rNVFNclZQeIdvSsXHVIVcHsfWpnfqfzg2gd1j0qJlS6Wy_QOmx3jsEl4ngNP1lc9ElOpnWr5HoI1N0Eco_5Uwd2xpK-UDUdrvwVO_ckHE-9tBOlb2OyUucSwPC17C8ZDuENJdCSeoaO3zQIVmrvFOUAw54CHLwWmeXXs1I8CkuyTtw21uFC4JcM-CM0moiV5rIOXoPCK6fF8kwCsIIMVZ6EWPY5TKxeK-a1FcWKOAwqIOcV8RTAgY2Dvd5XHgedNuYMeeZQcS5N_EZGhTxqX22A",
  "payload": ""
}
2025-02-22 13:36:46,624:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2243553505/479847063865 HTTP/1.1" 200 1423
2025-02-22 13:36:46,624:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 22 Feb 2025 13:36:46 GMT
Content-Type: application/json
Content-Length: 1423
Connection: keep-alive
Boulder-Requester: 2243553505
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: bmVxADwstmQfZQ2PqUGU9mUnRDQrpHsoRjXgqv-rxWdyLFS9hEo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "vaxelaire.fr"
  },
  "status": "invalid",
  "expires": "2025-03-01T13:36:45Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2243553505/479847063865/hlRTKQ",
      "status": "invalid",
      "validated": "2025-02-22T13:36:45Z",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "91.108.113.88: Fetching http://vaxelaire.fr/.well-known/acme-challenge/XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0: Error getting validation data",
        "status": 400
      },
      "token": "XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0",
      "validationRecord": [
        {
          "url": "http://vaxelaire.fr/.well-known/acme-challenge/XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0",
          "hostname": "vaxelaire.fr",
          "port": "80",
          "addressesResolved": [
            "91.108.113.88",
            "2a02:4780:28:d15a::1"
          ],
          "addressUsed": "2a02:4780:28:d15a::1"
        },
        {
          "url": "http://vaxelaire.fr/.well-known/acme-challenge/XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0",
          "hostname": "vaxelaire.fr",
          "port": "80",
          "addressesResolved": [
            "91.108.113.88",
            "2a02:4780:28:d15a::1"
          ],
          "addressUsed": "91.108.113.88"
        }
      ]
    }
  ]
}
2025-02-22 13:36:46,625:DEBUG:acme.client:Storing nonce: bmVxADwstmQfZQ2PqUGU9mUnRDQrpHsoRjXgqv-rxWdyLFS9hEo
2025-02-22 13:36:46,625:INFO:certbot._internal.auth_handler:Challenge failed for domain vaxelaire.fr
2025-02-22 13:36:46,625:INFO:certbot._internal.auth_handler:http-01 challenge for vaxelaire.fr
2025-02-22 13:36:46,625:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: vaxelaire.fr
  Type:   connection
  Detail: 91.108.113.88: Fetching http://vaxelaire.fr/.well-known/acme-challenge/XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0: Error getting validation data

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2025-02-22 13:36:46,626:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-02-22 13:36:46,626:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-02-22 13:36:46,626:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-02-22 13:36:46,626:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/XutO_cCnQKvJWgY-SOHaUvOWCUcNm14kwlhTB-a42u0
2025-02-22 13:36:46,627:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2025-02-22 13:36:46,627:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-02-22 13:36:46,629:ERROR:certbot._internal.log:Some challenges have failed.
